import { K2D } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/Navigation/Footer";
import NextTopLoader from 'nextjs-toploader';


const k2d = K2D({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Syria Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body
        className={`${k2d.className} flex flex-col min-h-screen max-w-screen-2xl mx-auto`}
      >
        <Navbar />
        <main className="relative overflow-hidden flex-1">
        <NextTopLoader
         color="#ef4444"
         height={3.6}
         showSpinner={ false } 
        />
          {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
